import ChakraContext from "@/components/context/ChakraContext";
import { Container, Grid, GridItem } from "@chakra-ui/react";
import Footer from "@/components/navigation/Footer";
import Header from "@/components/navigation/Header";

export const metadata = {
  title: "Sin City Jacks",
  // description: "Generated by create next app", 150-160 characters
};

export default function RootLayout({ children }) {
  return (
    <ChakraContext>
      <html lang={"en"}>
        <body>
          <Grid gridTemplateRows={"1fr auto"} h={"100vh"} gap={4} py={8}>
            <GridItem>
              <Container>
                <Header />
                {children}
              </Container>
            </GridItem>
            <GridItem>
              <Container>
                <Footer />
              </Container>
            </GridItem>
          </Grid>
        </body>
      </html>
    </ChakraContext>
  );
}
