import ChakraContext from "@/components/context/ChakraContext";

export const metadata = {
  title: "Sin City Jacks",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ChakraContext>
      <html lang={"en"}>
        <body>{children}</body>
      </html>
    </ChakraContext>
  );
}
