import { ChakraProvider } from "@chakra-ui/react";

export const metadata = {
  title: "Sin City Jacks",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ChakraProvider>
      <html lang={"en"}>
        <body>{children}</body>
      </html>
    </ChakraProvider>
  );
}
